version: '3'

services:
  eoapi-remote-server-test:
    # build: 从当前路径构建镜像
    # build: .
    image: eolinker/eoapi-remote-server:1.9.0
    container_name: eoapi-remote-server-test
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3001:3001'
    networks:
      - eoapi_net

  eoapi:
    image: eolinker/eoapi:1.9.0-dev
    container_name: eoapi-dev
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3002:80'
    networks:
      - eoapi_net

  eoapi-test-server:
    image: eolinker/eoapi-test-server:1.9.0-dev
    container_name: eoapi-test-server-dev
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '42011:4201'
      - '42022:4202'
    networks:
      - eoapi_net

networks:
  eoapi_net:
    name: eoapi_net
