version: '3'

services:
  eoapi-remote-server:
    # build: 从当前路径构建镜像
    # build: .
    image: eolinker/eoapi-remote-server:1.9.0
    container_name: eoapi-remote-server
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    environment:
      # 服务配置
      EOAPI_SERVER_PORT: 3000
      EOAPI_API_PREFIX: /api
      MYSQL_HOST: host.docker.internal # 数据库地址
      TZ: Asia/Shanghai
      # 数据库配置
      MYSQL_PORT: 33066 # 数据库端口号
      MYSQL_USERNAME: root
      MYSQL_DATABASE: eoapi
      MYSQL_PASSWORD: 123456a.
      MYSQL_ROOT_PASSWORD: 123456a.
      # swagger配置
      SWAGGER_PATH: swagger-docs
      SWAGGER_ENABLE: true
      SWAGGER_VERSION: 1.0
      SWAGGER_TITLE: Eoapi-remote-server API文档
      SWAGGER_DESC: Eoapi remote server API document。
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 3000:3000
    # 当前服务启动之前先要把depends_on指定的服务启动起来才行
    depends_on:
      - mysql
    networks:
      - eoapi_net

  mysql:
    image: mysql:latest
    container_name: eoapi-mysql
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci #设置utf8字符集
    environment:
      TZ: Asia/Shanghai
      MYSQL_USERNAME: root
      MYSQL_DATABASE: eoapi
      MYSQL_PASSWORD: 123456a.
      MYSQL_ROOT_PASSWORD: 123456a.
    ports:
      - 33066:3306
    volumes:
      - ./sample/mysql/:/var/lib/mysql/ # ./sample/mysql/路径可以替换成自己的路径
    networks:
      - eoapi_net

  eoapi:
    image: eolinker/eoapi:1.9.0-dev
    container_name: eoapi:1.9.0-dev
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3002:80'
    # volumes:
    # - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - eoapi_net

  eoapi-test-server:
    image: eolinker/eoapi-test-server:1.9.0-dev
    container_name: eoapi-test-server:1.9.0-dev
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '42011:4201'
      - '42022:4202'
    networks:
      - eoapi_net

networks:
  eoapi_net:
    name: eoapi_net
