name: Build Latest Image

on:
  push:
  tags:
    - 'v*.*.*'

env:
  VERSION: ${{ github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
         run: echo "tag=${ VERSION##*v }" >> $GITHUB_OUTPUT
        with:
          push: true
          tags: eolinker/eoapi-remote-server:latest,eolinker/eoapi-remote-server:${{ steps.vars.outputs.tag }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
